version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - API_KEY
      - API_SECRET
      - SUPPLIER_ID
      - WEBHOOK_SECRET
      - WEBHOOK_BASE_URL
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"