"""Add StockPushLog table for tracking Trendyol stock sync

Revision ID: add_stock_push_log
Revises: 
Create Date: 2025-11-03

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_stock_push_log'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_push_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('push_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('batch_count', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_push_log_push_time'), 'stock_push_log', ['push_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_push_log_push_time'), table_name='stock_push_log')
    op.drop_table('stock_push_log')
    # ### end Alembic commands ###
